name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-schema-changes:
    name: Check for Schema Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
      - name: Regenerate the schema
        run: pixi run schema
      - name: Check for schema changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]
          then
            echo "::error::The schema is out of date. Please run 'pixi run schema' and commit the changes."
            exit 1
          fi

  check-requirements-txt:
    name: Check requirements.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          run-install: false
      - name: Sync to requirements.txt
        run: ./.github/scripts/sync-deps.sh
      - name: Check for changes
        run: |
          git diff --exit-code
          if [ $? -eq 1 ]
          then
            echo "::error::The requirements.txt is out of date. Please run './.github/scripts/sync-deps.sh' and commit the changes."
            exit 1
          fi

  check-deps:
    name: Check pixi.toml in sync with pyproject.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          run-install: false
      - name: Check Dependencies
        run: ./.github/scripts/check-deps.sh
